name: Run Weather Bot
on:
  schedule:
    - cron: '0 23 * * *' # 매일 아침 8시(UTC 기준 23시)에 실행
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests telepot
      - name: Run script
        run: python weather.py
